In [1]:
import pandas as pd

In [2]:
# read data
diabetes = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Diabetes.csv')

In [3]:
diabetes.head()

,pregnancies,glucose,diastolic,triceps,insulin,bmi,dpf,age,diabetes
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [5]:
diabetes.columns

Index(['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes'],
      dtype='object')

In [6]:
y = diabetes['diabetes']

In [18]:
x = diabetes.drop(['diabetes'],axis = 1)

In [19]:
x = diabetes[['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age']]

In [17]:
x

     pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age
0              6      148         72       35        0  33.6  0.627   50
1              1       85         66       29        0  26.6  0.351   31
2              8      183         64        0        0  23.3  0.672   32
3              1       89         66       23       94  28.1  0.167   21
4              0      137         40       35      168  43.1  2.288   33
..           ...      ...        ...      ...      ...   ...    ...  ...
763           10      101         76       48      180  32.9  0.171   63
764            2      122         70       27        0  36.8  0.340   27
765            5      121         72       23      112  26.2  0.245   30
766            1      126         60        0        0  30.1  0.349   47
767            1       93         70       31        0  30.4  0.315   23

[768 rows x 8 columns]

In [10]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: diabetes, Length: 768, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split

In [27]:
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size = 0.2,random_state = 2529)

In [28]:
train_x.shape,train_y.shape,test_x.shape,test_y.shape

((614, 8), (614,), (154, 8), (154,))

In [31]:
train_x

     pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age
517            7      125         86        0        0  37.6  0.304   51
286            5      155         84       44      545  38.7  0.619   34
614           11      138         74       26      144  36.1  0.557   50
256            3      111         56       39        0  30.1  0.557   30
316            3       99         80       11       64  19.3  0.284   30
..           ...      ...        ...      ...      ...   ...    ...  ...
584            8      124         76       24      600  28.7  0.687   52
740           11      120         80       37      150  42.3  0.785   48
399            3      193         70       31        0  34.9  0.241   25
562            1       87         68       34       77  37.6  0.401   24
352            3       61         82       28        0  34.4  0.243   46

[614 rows x 8 columns]

In [69]:
# model 1
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression(max_iter = 500)
model1.fit(train_x,train_y)

LogisticRegression(max_iter=500)

In [70]:
# model 2
from sklearn.tree import DecisionTreeClassifier
model2 = DecisionTreeClassifier()
model2.fit(train_x,train_y)

DecisionTreeClassifier()

In [72]:
# model 3
from sklearn.neighbors import KNeighborsClassifier
model3 = KNeighborsClassifier(n_neighbors = 10)
model3.fit(train_x,train_y)

KNeighborsClassifier(n_neighbors=10)

In [74]:
model1_pred = model1.predict(test_x)
model2_pred = model2.predict(test_x)
model3_pred = model3.predict(test_x)

In [75]:
model1.score(test_x,test_y)

0.7727272727272727

In [76]:
# Step 8 : model accuracy
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [81]:
accuracy_score(test_y,model1_pred)

0.7727272727272727

In [79]:
accuracy_score(test_y,model2_pred)

0.6623376623376623

In [80]:
accuracy_score(test_y,model3_pred)

0.6688311688311688